"""Defaults for categorical-dependency discovery."""

DEFAULT_MODEL = "gpt-5.6-luna"
DEFAULT_VIOLATION_THRESHOLD = 0.005
DEFAULT_MAX_DETERMINANTS = 3
DEFAULT_MAX_AGENT_TURNS = 40
DEFAULT_MAX_COUNTEREXAMPLES = 20
DEFAULT_MAX_CONFIGURATION_SUMMARIES = 20
DEFAULT_MAX_ATOMIC_CONFIGURATIONS = 100_000
